-- MySQL Script generated by MySQL Workbench
-- 08/09/15 11:01:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema xml2015
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `xml2015` ;

-- -----------------------------------------------------
-- Schema xml2015
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `xml2015` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `xml2015` ;

-- -----------------------------------------------------
-- Table `xml2015`.`brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xml2015`.`brand` ;

CREATE TABLE IF NOT EXISTS `xml2015`.`brand` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `brandName` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `description` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `xml2015`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xml2015`.`user` ;

CREATE TABLE IF NOT EXISTS `xml2015`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `username` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `password` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `fullname` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '',
  `gender` TINYINT(255) NULL DEFAULT NULL COMMENT '',
  `locale` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '',
  `lastLogin` DATETIME NOT NULL COMMENT '',
  `createTime` DATETIME NOT NULL COMMENT '',
  `updateTime` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `xml2015`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xml2015`.`customer` ;

CREATE TABLE IF NOT EXISTS `xml2015`.`customer` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `userId` INT(11) NULL DEFAULT NULL COMMENT '',
  `customerName` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `address` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `mobile` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `FK_Customer_User` (`userId` ASC)  COMMENT '',
  CONSTRAINT `FK_Customer_User`
    FOREIGN KEY (`userId`)
    REFERENCES `xml2015`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `xml2015`.`devicetype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xml2015`.`devicetype` ;

CREATE TABLE IF NOT EXISTS `xml2015`.`devicetype` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `deviceType` TINYINT(4) NOT NULL COMMENT '0: MOBILE \\n 1: TABLET \\n2: ACCESSORY',
  `description` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `xml2015`.`importschedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xml2015`.`importschedule` ;

CREATE TABLE IF NOT EXISTS `xml2015`.`importschedule` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `scheduleName` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '',
  `startTime` DATETIME NULL DEFAULT NULL COMMENT '',
  `endTime` DATETIME NULL DEFAULT NULL COMMENT '',
  `lastImportId` INT(11) NULL DEFAULT NULL COMMENT '',
  `status` TINYINT(4) NULL DEFAULT '0' COMMENT '0: ACTIVE 1: INACTIVE 2: RUNNING',
  `crawlingUrl` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `xml2015`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xml2015`.`product` ;

CREATE TABLE IF NOT EXISTS `xml2015`.`product` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `deviceTypeId` INT(11) NOT NULL COMMENT '',
  `brandId` INT(11) NOT NULL COMMENT '',
  `name` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `barcode` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `price` DECIMAL(10,0) NOT NULL COMMENT '',
  `status` TINYINT(4) NULL DEFAULT '0' COMMENT '0: ACTIVE\\n 1: INACTIVE',
  `createUser` INT(11) NOT NULL COMMENT '',
  `createTime` DATETIME NOT NULL COMMENT '',
  `updateTime` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `FK_DeviceType` (`deviceTypeId` ASC)  COMMENT '',
  INDEX `FK_Branch` (`brandId` ASC)  COMMENT '',
  INDEX `FK_CreateUser` (`createUser` ASC)  COMMENT '',
  CONSTRAINT `FK_Branch`
    FOREIGN KEY (`brandId`)
    REFERENCES `xml2015`.`brand` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CreateUser`
    FOREIGN KEY (`createUser`)
    REFERENCES `xml2015`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_DeviceType`
    FOREIGN KEY (`deviceTypeId`)
    REFERENCES `xml2015`.`devicetype` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `xml2015`.`inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xml2015`.`inventory` ;

CREATE TABLE IF NOT EXISTS `xml2015`.`inventory` (
  `id` INT(11) NOT NULL COMMENT '',
  `productId` INT(11) NOT NULL COMMENT '',
  `total` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `FK_Inventory_Product` (`productId` ASC)  COMMENT '',
  CONSTRAINT `FK_Inventory_Product`
    FOREIGN KEY (`productId`)
    REFERENCES `xml2015`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `xml2015`.`inventorytracking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xml2015`.`inventorytracking` ;

CREATE TABLE IF NOT EXISTS `xml2015`.`inventorytracking` (
  `id` INT(11) NOT NULL COMMENT '',
  `productId` INT(11) NOT NULL COMMENT '',
  `type` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '0: IMPORT \\n 1: EXPORT',
  `quantity` INT(255) NOT NULL COMMENT '',
  `createDate` DATETIME NOT NULL COMMENT '',
  `stockInUser` INT(11) NULL DEFAULT NULL COMMENT '',
  `stockOutUser` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `FK_StockIn` (`stockInUser` ASC)  COMMENT '',
  INDEX `FK_StockOut` (`stockOutUser` ASC)  COMMENT '',
  INDEX `FK_InventoryTracking_Product` (`productId` ASC)  COMMENT '',
  CONSTRAINT `FK_InventoryTracking_Product`
    FOREIGN KEY (`productId`)
    REFERENCES `xml2015`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_StockIn`
    FOREIGN KEY (`stockInUser`)
    REFERENCES `xml2015`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_StockOut`
    FOREIGN KEY (`stockOutUser`)
    REFERENCES `xml2015`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `xml2015`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xml2015`.`order` ;

CREATE TABLE IF NOT EXISTS `xml2015`.`order` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `orderNo` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `barcode` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '',
  `customerId` INT(11) NOT NULL COMMENT '',
  `createDate` DATETIME NOT NULL COMMENT '',
  `approvedDate` DATETIME NULL DEFAULT NULL COMMENT '',
  `approvedUser` INT(255) NULL DEFAULT NULL COMMENT '',
  `status` TINYINT(255) NOT NULL DEFAULT '0' COMMENT '0: ENTRY \\n 1: APPROVED \\n 2: CANCEL 3: REFUSE',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `FK_Order_Customer` (`customerId` ASC)  COMMENT '',
  CONSTRAINT `FK_Order_Customer`
    FOREIGN KEY (`customerId`)
    REFERENCES `xml2015`.`customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `xml2015`.`orderdetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xml2015`.`orderdetail` ;

CREATE TABLE IF NOT EXISTS `xml2015`.`orderdetail` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `orderId` INT(11) NOT NULL COMMENT '',
  `productId` INT(11) NOT NULL COMMENT '',
  `quantity` INT(11) NOT NULL COMMENT '',
  `status` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '0: ENTRY \\n 1: DELIVERED',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `FK_OrderDetail_ProductId` (`productId` ASC)  COMMENT '',
  INDEX `FK_OrderDetail_Order` (`orderId` ASC)  COMMENT '',
  CONSTRAINT `FK_OrderDetail_Order`
    FOREIGN KEY (`orderId`)
    REFERENCES `xml2015`.`order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_OrderDetail_ProductId`
    FOREIGN KEY (`productId`)
    REFERENCES `xml2015`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `xml2015`.`propertykey`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xml2015`.`propertykey` ;

CREATE TABLE IF NOT EXISTS `xml2015`.`propertykey` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `propertyKeyName` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `description` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `xml2015`.`productinfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xml2015`.`productinfo` ;

CREATE TABLE IF NOT EXISTS `xml2015`.`productinfo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `productId` INT(11) NOT NULL COMMENT '',
  `propertyKeyId` INT(11) NULL DEFAULT NULL COMMENT '',
  `propertyValue` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `FK_Product` (`productId` ASC)  COMMENT '',
  INDEX `FK_PropertyKey` (`propertyKeyId` ASC)  COMMENT '',
  CONSTRAINT `FK_Product`
    FOREIGN KEY (`productId`)
    REFERENCES `xml2015`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PropertyKey`
    FOREIGN KEY (`propertyKeyId`)
    REFERENCES `xml2015`.`propertykey` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `xml2015`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xml2015`.`role` ;

CREATE TABLE IF NOT EXISTS `xml2015`.`role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `roleName` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `roleDescription` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `xml2015`.`userrole`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `xml2015`.`userrole` ;

CREATE TABLE IF NOT EXISTS `xml2015`.`userrole` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `roleId` INT(11) NOT NULL COMMENT '',
  `userId` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `FK_User` (`userId` ASC)  COMMENT '',
  INDEX `FK_Role` (`roleId` ASC)  COMMENT '',
  CONSTRAINT `FK_Role`
    FOREIGN KEY (`roleId`)
    REFERENCES `xml2015`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_User`
    FOREIGN KEY (`userId`)
    REFERENCES `xml2015`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
